"""removed image column

Revision ID: 6f1fa9464880
Revises: 749a056a8a56
Create Date: 2023-08-10 17:59:49.444366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1fa9464880'
down_revision = '749a056a8a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
